# Gold Dataset Analysis

## Objective
Load the `gold_dataset.parquet` file and sort it by **machine** (`machine_id_std`) and **time** (`window_start`).


### Dataset Structure
- **Rows**: 134,280
- **Columns**: 100
- **Key columns for sorting**:
  - `machine_id_std`: Machine identifier (e.g., `MACH-01`)
  - `window_start`: Timestamp (datetime) for the start of the measurement window

## Install required libraires
```bash
uv add pandas pyarrow jupyter 
uv add scikit-learn
```

In [2]:
# Import required libraries
import pandas as pd

## Step 1: Load the Dataset from Parquet

Load the dataset from `gold_dataset.parquet` using `pandas`.

In [3]:
# Load the dataset from Parquet
file_path = 'artifacts/ingestions/datas/gold_dataset.parquet'
df = pd.read_parquet(file_path)

# Display basic info
print('Dataset shape:', df.shape)
print('\nFirst 5 rows:')
display(df.head())

Dataset shape: (134280, 100)

First 5 rows:

,machine_id_std,window_start,temp_mean_1h,temp_max_1h,pressure_mean_1h,pressure_max_1h,voltage_mean_1h,voltage_max_1h,rotation_mean_1h,rotation_max_1h,...,maintenance_count_prev_30d,future_incident_count_6h,label_failure_next_6h,future_incident_count_12h,label_failure_next_12h,future_incident_count_24h,label_failure_next_24h,future_incident_count_48h,label_failure_next_48h,split_set
0,MACH-01,2025-06-01 00:00:00,46.340,46.340,198.203,198.203,227.568,227.568,1541.787,1541.787,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
1,MACH-01,2025-06-01 01:00:00,48.762,48.762,198.295,198.295,227.480,227.480,1537.860,1537.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
2,MACH-01,2025-06-01 02:00:00,51.352,51.352,199.545,199.545,228.680,228.680,1584.660,1584.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
3,MACH-01,2025-06-01 03:00:00,49.512,49.512,201.641,201.641,228.440,228.440,1588.960,1588.960,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
4,MACH-01,2025-06-01 04:00:00,51.982,51.982,200.157,200.157,227.840,227.840,1548.660,1548.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train

## Step 2: Inspect Column Names and Data Types

Verify the columns for **machine** (`machine_id_std`) and **time** (`window_start`).

In [4]:
# Check column names and data types
print('Columns:', df.columns.tolist())
print('\nData types:')
print(df.dtypes)

Columns: ['machine_id_std', 'window_start', 'temp_mean_1h', 'temp_max_1h', 'pressure_mean_1h', 'pressure_max_1h', 'voltage_mean_1h', 'voltage_max_1h', 'rotation_mean_1h', 'rotation_max_1h', 'pieces_produced_sum_1h', 'window_end', 'temp_mean_6h', 'temp_max_6h', 'temp_std_6h', 'pressure_mean_6h', 'pressure_max_6h', 'pressure_std_6h', 'voltage_mean_6h', 'voltage_max_6h', 'voltage_std_6h', 'rotation_mean_6h', 'rotation_max_6h', 'rotation_std_6h', 'temp_mean_12h', 'temp_max_12h', 'temp_std_12h', 'pressure_mean_12h', 'pressure_max_12h', 'pressure_std_12h', 'voltage_mean_12h', 'voltage_max_12h', 'voltage_std_12h', 'rotation_mean_12h', 'rotation_max_12h', 'rotation_std_12h', 'temp_mean_24h', 'temp_max_24h', 'temp_std_24h', 'pressure_mean_24h', 'pressure_max_24h', 'pressure_std_24h', 'voltage_mean_24h', 'voltage_max_24h', 'voltage_std_24h', 'rotation_mean_24h', 'rotation_max_24h', 'rotation_std_24h', 'temp_trend_6h', 'pressure_trend_6h', 'voltage_trend_6h', 'rotation_trend_6h', 'temp_zscore_24h', 'temp_delta_1h', 'temp_delta_3h', 'pressure_delta_1h', 'pressure_delta_3h', 'rotation_delta_1h', 'rotation_delta_3h', 'voltage_delta_1h', 'voltage_delta_3h', 'temp_zscore_machine', 'pressure_zscore_machine', 'pieces_produced_sum_24h', 'capacity_utilization_pct', 'incident_count_1h', 'incident_max_severity_1h', 'incident_count_prev_24h', 'incident_max_severity_prev_24h', 'incident_count_prev_7d', 'hours_since_last_incident', 'type_surchauffe', 'type_baisse_pression', 'type_vibration', 'type_bruit_mecanique', 'type_surconsommation', 'type_blocage_mecanique', 'type_alarme_capteur', 'type_arret_urgence', 'type_defaut_qualite', 'type_surchauffe_count_prev_24h', 'type_baisse_pression_count_prev_24h', 'type_vibration_count_prev_24h', 'type_bruit_mecanique_count_prev_24h', 'type_surconsommation_count_prev_24h', 'type_blocage_mecanique_count_prev_24h', 'type_alarme_capteur_count_prev_24h', 'type_arret_urgence_count_prev_24h', 'type_defaut_qualite_count_prev_24h', 'days_since_last_maintenance', 'maintenance_count_prev_30d', 'future_incident_count_6h', 'label_failure_next_6h', 'future_incident_count_12h', 'label_failure_next_12h', 'future_incident_count_24h', 'label_failure_next_24h', 'future_incident_count_48h', 'label_failure_next_48h', 'split_set']

Data types:
machine_id_std                     category
window_start                 datetime64[us]
temp_mean_1h                        float64
temp_max_1h                         float64
pressure_mean_1h                    float64
                                  ...
future_incident_count_24h           float64
label_failure_next_24h                 bool
future_incident_count_48h           float64
label_failure_next_48h                 bool
split_set                          category
Length: 100, dtype: object

## Step 3: Sort by Machine and Time

Sort the DataFrame by `machine_id_std` (ascending) and `window_start` (ascending).

In [10]:
# Sort the DataFrame
df_sorted = df.sort_values(by=['machine_id_std', 'window_start'])

# Verify the sorted data
print('First 15 rows after sorting:')
display(df_sorted.head(15))

First 15 rows after sorting:

,machine_id_std,window_start,temp_mean_1h,temp_max_1h,pressure_mean_1h,pressure_max_1h,voltage_mean_1h,voltage_max_1h,rotation_mean_1h,rotation_max_1h,...,maintenance_count_prev_30d,future_incident_count_6h,label_failure_next_6h,future_incident_count_12h,label_failure_next_12h,future_incident_count_24h,label_failure_next_24h,future_incident_count_48h,label_failure_next_48h,split_set
0,MACH-01,2025-06-01 00:00:00,46.340,46.340,198.203,198.203,227.568,227.568,1541.787,1541.787,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
1,MACH-01,2025-06-01 01:00:00,48.762,48.762,198.295,198.295,227.480,227.480,1537.860,1537.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
2,MACH-01,2025-06-01 02:00:00,51.352,51.352,199.545,199.545,228.680,228.680,1584.660,1584.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
3,MACH-01,2025-06-01 03:00:00,49.512,49.512,201.641,201.641,228.440,228.440,1588.960,1588.960,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
4,MACH-01,2025-06-01 04:00:00,51.982,51.982,200.157,200.157,227.840,227.840,1548.660,1548.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
5,MACH-01,2025-06-01 05:00:00,50.402,50.402,199.914,199.914,227.500,227.500,1554.760,1554.760,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
6,MACH-01,2025-06-01 06:00:00,49.732,49.732,198.551,198.551,227.650,227.650,1555.760,1555.760,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
7,MACH-01,2025-06-01 07:00:00,50.292,50.292,199.972,199.972,226.890,226.890,1593.860,1593.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
8,MACH-01,2025-06-01 08:00:00,48.672,48.672,200.262,200.262,226.050,226.050,1567.860,1567.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
9,MACH-01,2025-06-01 09:00:00,46.692,46.692,199.051,199.051,225.110,225.110,1532.060,1532.060,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
10,MACH-01,2025-06-01 10:00:00,46.772,46.772,198.124,198.124,227.030,227.030,1550.860,1550.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
11,MACH-01,2025-06-01 11:00:00,44.972,44.972,198.291,198.291,225.830,225.830,1556.660,1556.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
12,MACH-01,2025-06-01 12:00:00,43.322,43.322,197.290,197.290,225.490,225.490,1507.260,1507.260,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
13,MACH-01,2025-06-01 13:00:00,42.762,42.762,198.082,198.082,225.830,225.830,1539.660,1539.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
14,MACH-01,2025-06-01 14:00:00,39.582,39.582,198.388,198.388,225.240,225.240,1523.960,1523.960,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train

## Step 4: Verify Sorting for a Specific Machine

Check if the data is correctly sorted by machine and time.

In [ ]:
# Check sorting for a specific machine
sample_machine = df_sorted['machine_id_std'].iloc[0]
machine_data = df_sorted[df_sorted['machine_id_std'] == sample_machine]

print(f'Sample machine: {sample_machine}')
print(f'Number of records for {sample_machine}: {len(machine_data)}')
print('\nFirst 5 records for this machine:')
display(machine_data.head())

Sample machine: MACH-01
Number of records for MACH-01: 8952

First 5 records for this machine:

,machine_id_std,window_start,temp_mean_1h,temp_max_1h,pressure_mean_1h,pressure_max_1h,voltage_mean_1h,voltage_max_1h,rotation_mean_1h,rotation_max_1h,...,maintenance_count_prev_30d,future_incident_count_6h,label_failure_next_6h,future_incident_count_12h,label_failure_next_12h,future_incident_count_24h,label_failure_next_24h,future_incident_count_48h,label_failure_next_48h,split_set
0,MACH-01,2025-06-01 00:00:00,46.340,46.340,198.203,198.203,227.568,227.568,1541.787,1541.787,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
1,MACH-01,2025-06-01 01:00:00,48.762,48.762,198.295,198.295,227.480,227.480,1537.860,1537.860,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
2,MACH-01,2025-06-01 02:00:00,51.352,51.352,199.545,199.545,228.680,228.680,1584.660,1584.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
3,MACH-01,2025-06-01 03:00:00,49.512,49.512,201.641,201.641,228.440,228.440,1588.960,1588.960,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train
4,MACH-01,2025-06-01 04:00:00,51.982,51.982,200.157,200.157,227.840,227.840,1548.660,1548.660,...,0,0.0,False,0.0,False,0.0,False,0.0,False,train

## Step 5: Export Sorted Data (Optional)

Save the sorted DataFrame to a new Parquet file.

In [ ]:
# Export to Parquet
output_parquet_path = 'artifacts/ingestions/datas/gold_dataset_sorted.parquet'
df_sorted.to_parquet(output_parquet_path, index=False)
print(f'Sorted data exported to: {output_parquet_path}')

## Summary

- The dataset was loaded successfully from `gold_dataset.parquet`.
- It was sorted by `machine_id_std` and `window_start`.
- The sorted data was exported to `gold_dataset_sorted.parquet`.

# NEXT STEP

## Deliverables
- [ ] Jupyter Notebook (`analysis.ipynb`) with all steps implemented.
- [ ] Processed datasets (`X_train`, `X_val`, `X_test`, `y_train`, `y_val`, `y_test`).
- [ ] Preprocessing pipeline (imputation + standardization).

---
## Notes
- **Leakage Columns**: Any column containing future information (e.g., `future_incident_count_*`, `label_failure_next_*`) must be excluded to avoid data leakage.
- **Identifiers**: Columns like `machine_id_std`, `window_start`, and `window_end` are not useful as features.
- **Temporal Split**: The `split_set` column provides a predefined temporal split (train < validation < test). Do not use random splitting.
- **Imputation**: Median imputation is used for numerical features to handle missing values.
- **Standardization**: Required for linear models (e.g., logistic regression, SVM).
- **Horizon Selection**: Choose the horizon (e.g., `label_failure_next_24h`) based on the predictive maintenance task requirements.

In [11]:
# Define columns to exclude
exclude_columns = [
    # Identifiers
    'machine_id_std', 'window_start', 'window_end',
    # Leakage columns (future information)
    'future_incident_count_6h', 'label_failure_next_6h',
    'future_incident_count_12h', 'label_failure_next_12h',
    'future_incident_count_24h', 'label_failure_next_24h',
    'future_incident_count_48h', 'label_failure_next_48h',
    # Incident counts (potential leakage)
    'incident_count_1h', 'incident_max_severity_1h',
    'incident_count_prev_24h', 'incident_max_severity_prev_24h',
    'incident_count_prev_7d', 'hours_since_last_incident',
    # Type-specific incident counts (potential leakage)
    'type_surchauffe_count_prev_24h', 'type_baisse_pression_count_prev_24h',
    'type_vibration_count_prev_24h', 'type_bruit_mecanique_count_prev_24h',
    'type_surconsommation_count_prev_24h', 'type_blocage_mecanique_count_prev_24h',
    'type_alarme_capteur_count_prev_24h', 'type_arret_urgence_count_prev_24h',
    'type_defaut_qualite_count_prev_24h',
    # Maintenance columns (potential leakage)
    'days_since_last_maintenance', 'maintenance_count_prev_30d',
    # Split column (to be used later)
    'split_set'
]

# Exclude columns from the DataFrame
features_df = df.drop(columns=exclude_columns)

# Verify remaining columns
print("Remaining columns:", features_df.columns.tolist())

Remaining columns: ['temp_mean_1h', 'temp_max_1h', 'pressure_mean_1h', 'pressure_max_1h', 'voltage_mean_1h', 'voltage_max_1h', 'rotation_mean_1h', 'rotation_max_1h', 'pieces_produced_sum_1h', 'temp_mean_6h', 'temp_max_6h', 'temp_std_6h', 'pressure_mean_6h', 'pressure_max_6h', 'pressure_std_6h', 'voltage_mean_6h', 'voltage_max_6h', 'voltage_std_6h', 'rotation_mean_6h', 'rotation_max_6h', 'rotation_std_6h', 'temp_mean_12h', 'temp_max_12h', 'temp_std_12h', 'pressure_mean_12h', 'pressure_max_12h', 'pressure_std_12h', 'voltage_mean_12h', 'voltage_max_12h', 'voltage_std_12h', 'rotation_mean_12h', 'rotation_max_12h', 'rotation_std_12h', 'temp_mean_24h', 'temp_max_24h', 'temp_std_24h', 'pressure_mean_24h', 'pressure_max_24h', 'pressure_std_24h', 'voltage_mean_24h', 'voltage_max_24h', 'voltage_std_24h', 'rotation_mean_24h', 'rotation_max_24h', 'rotation_std_24h', 'temp_trend_6h', 'pressure_trend_6h', 'voltage_trend_6h', 'rotation_trend_6h', 'temp_zscore_24h', 'temp_delta_1h', 'temp_delta_3h', 'pressure_delta_1h', 'pressure_delta_3h', 'rotation_delta_1h', 'rotation_delta_3h', 'voltage_delta_1h', 'voltage_delta_3h', 'temp_zscore_machine', 'pressure_zscore_machine', 'pieces_produced_sum_24h', 'capacity_utilization_pct', 'type_surchauffe', 'type_baisse_pression', 'type_vibration', 'type_bruit_mecanique', 'type_surconsommation', 'type_blocage_mecanique', 'type_alarme_capteur', 'type_arret_urgence', 'type_defaut_qualite']

In [ ]:
# Select the horizon (e.g., 24h)
horizon = 'label_failure_next_48h'

# Extract the target variable
y = df[horizon].astype(int)  # Convert boolean to 0/1

# Verify target distribution
print("Target distribution:")
print(y.value_counts())

# Split the data using the 'split_set' column
train_df = df[df['split_set'] == 'train']
val_df = df[df['split_set'] == 'validation']
test_df = df[df['split_set'] == 'test']

# Split features and target for each set
X_train = train_df.drop(columns=exclude_columns + [horizon])
y_train = train_df[horizon].astype(int)

X_val = val_df.drop(columns=exclude_columns + [horizon])
y_val = val_df[horizon].astype(int)

X_test = test_df.drop(columns=exclude_columns + [horizon])
y_test = test_df[horizon].astype(int)

# Verify shapes
print(f"Train shape: {X_train.shape}, {y_train.shape}")
print(f"Validation shape: {X_val.shape}, {y_val.shape}")
print(f"Test shape: {X_test.shape}, {y_test.shape}")

Target distribution:
label_failure_next_48h
0    100002
1     34278
Name: count, dtype: int64
Train shape: (93990, 71), (93990,)
Validation shape: (20145, 71), (20145,)
Test shape: (20145, 71), (20145,)

In [17]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

# Create a pipeline for imputation and standardization
pipeline = Pipeline([
    ('imputer', SimpleImputer(strategy='median')),  # Impute NaN with median
    ('scaler', StandardScaler())  # Standardize features
])

# Fit and transform the training data
X_train_processed = pipeline.fit_transform(X_train)

# Transform validation and test data (using the same pipeline)
X_val_processed = pipeline.transform(X_val)
X_test_processed = pipeline.transform(X_test)

# Verify no NaN values remain
print("NaN values in X_train:", pd.isna(X_train_processed).sum().sum())
print("NaN values in X_val:", pd.isna(X_val_processed).sum().sum())
print("NaN values in X_test:", pd.isna(X_test_processed).sum().sum())

NaN values in X_train: 0
NaN values in X_val: 0
NaN values in X_test: 0